Resources:
  UsersTable: ${file(./serverless/userTable.yml)}
  ProductsTable: ${file(./serverless/productsTable.yml)}
  OrdersTable: ${file(./serverless/ordersTable.yml)}
  OrdersStatusTable: ${file(./serverless/ordersStatusTable.yml)}
  DLQTable: ${file(./serverless/dlqTable.yml)}
  UpdateOrderQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: updateOrderQueue_${self:provider.stage}
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt: [UpdateOrderDLQ, Arn]
        maxReceiveCount: 2
  UpdateOrderDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: updateOrderDLQ_${self:provider.stage}
  OrdersErrorBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: orders-error-${self:provider.stage}
